spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/migration
    username: postgres
    password: 1596psql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/master-changelog.xml
